### ISSUE TITLE
infinitescroll is not a function

### ISSUE THREAD

**Issue by yokesh28** [davialexandre/yiinfinite-scroll#3]
i have getting this type of error

$(#posts).infinitescroll is not a function

in error console of firefox

and scroller is not working

**Comment by davialexandre** [comment]
Where and how did you installed the extension?

Can you check that you have the protected/extensions/yiinfinite-scroll/assets/jquery.infinitescroll.min.js?

**Comment by yokesh28** [comment]
ya... its having in there

**Comment by davialexandre** [comment]
Sorry, but I couldn't reproduce the error. Could you give me more details?

Can you try the use the extension in a clean yii app and tell me if you have the same issue?
Can you show me the code where you're using the extension?
Which version of the framework are you using? Which OS? Which PHP version?
