### ISSUE TITLE
Repeated Rows

### ISSUE THREAD

**Issue by ghost** [davialexandre/yiinfinite-scroll#7]
I am using version 1.2 and yii 1.1.14. I have followed your instructions and at first it seems to work. I have a model with 12 rows and that happened to be my page size. Everything works, scrolling produces no paging.

If I set the page size to 10, the first hit on the page shows all 12 rows not 10. Additional scrolling produces the same 12 rows an addition 2 times before stopping at 36 rows total.

I have checked the rows returned by the query and the count is 12.

Help?

**Comment by ghost** [comment]
To follow up, I found one mistake in my code. Everything seems to work correctly except the last page is repeated one time after what should be the end of the list. Any ideas what the problem might be? Thank you.

**Comment by ghost** [comment]
I think I fixed the problem, the current page wasn't being tracked resulting in one extra duplicate page at the end of a list. I just incremented currentPage in the run() function and everything works as advertised. Thanks for the great extension!

`````` php
public function run() {
        if($this->pageCount > 1) {
            $this->registerClientScript();
            $this->createInfiniteScrollScript();
            $this->renderNavigation();
            $this->currentPage++;
        }
```php
``````

**Comment by FilipeDornelas** [comment]
Had the same problem.
"$this->currentPage++;"  made the trick.

Thanks keithrdavis.
