### ISSUE TITLE
Data Provider and CListView Support

### ISSUE THREAD

**Issue by re1naldo** [davialexandre/yiinfinite-scroll#9]
Does yiinfinite-scroll support data provider and CListView? I tried to use yiinfinite-scroll as a pager of CListView and initially it worked fine, but afterAjaxUpdate event was not fired properly.

Someone has ever posted this issue in Yii forum (http://www.yiiframework.com/forum/index.php/topic/33029-yiinfinite-scroll-and-afterajaxupdate/), but there is no solution for him too.

**Comment by davialexandre** [comment]
It does, but since it have its own way to handle the page loading you need to disable ajaxUpdate and  afterAjaxUpdate and beforeAjaxUpdate won't be fired.

I just pushed a new release (1.3) and it introduces a new callback that it called when new content is loaded. Take a look at it!
